version: "3.1"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: api_postgres
    ports: 
    - "5432/5432"
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=friend_sphere_db
    volumes:
    - ./pgdata:/var/lib/postgres/data
    networks:
      - web_api


  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api  